### ISSUE TITLE
Add a trait for use in other classes

### ISSUE THREAD

**Issue by lukasbestle** [k-next/di#1]
For example the `router` implements everything manually. Maybe we should provide a trait?

**Comment by bastianallgeier** [comment]
I actually thought about making the entire Dependencies Class a trait, but then you can't extend it anymore. So maybe an additional trait would be great. Any ideas for a good name?

**Comment by lukasbestle** [comment]
You can actually extend traits like this:

```php
trait SomeTrait {
  use SomeOtherTrait;
}
```

**Comment by bastianallgeier** [comment]
Ahh, that's nice!

**Comment by distantnative** [comment]
-> https://github.com/k-next/toolkit/issues/33
